module.exports = (app) => {
    const userService = require('../services/UserService')
    const verifyAuth = require('../middleWare/verifyAuth')
    app.route('/register')
        .post(userService.register)
    app.route('/login')
        .post(userService.login)
    app.route('/user')
        .get(userService.getUser)
        .post(userService.addUser)
        .put(userService.updateUser)
        .delete(userService.deleteUser)
    app.route('/user/:id')
        .get(userService.getUserDetail)
}